version: '3'

tasks:
  # Unit Tests
  test:
    cmds:
      # The idiomatic way to disable test caching explicitly is to use -count=1
      - go test ./internal/... -count=1 -v --failfast

  # Linting
  lint:
    cmds:
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GOPATH/bin
      - $GOPATH/bin/golangci-lint run -v -c .golangci.yml ./...

  # E2E Tests
  build:
    cmds:
      - go build -o $GOPATH/bin/argocd-mcp-server main.go

  podman-compose-build:
    cmds:
      - podman-compose build
  
  podman-compose-up:
    cmds:
      - podman-compose up -d

  podman-compose-down:
    cmds:
      - podman-compose down
  
  test-e2e:
    deps:
      - build
      - podman-compose-up
    cmds:
      # The idiomatic way to disable test caching explicitly is to use -count=1
      - go test github.com/codeready-toolchain/argocd-mcp-server/test/e2e/... -count=1 -v -failfast

  build-image:
    cmds:
      - podman build --no-cache -t argocd-mcp-server:latest . -f Containerfile
  
  build-image-linux-amd64:
    cmds:
      - podman build --platform linux/amd64 --no-cache -t argocd-mcp-server:amd64 . -f Containerfile
