################################################################################################
# Builder image
# See https://hub.docker.com/_/golang/
################################################################################################
FROM golang:1.24 as argocd-mock-server-builder

WORKDIR /usr/src/app

# pre-copy/cache parent go.mod for pre-downloading dependencies and only redownloading them in subsequent builds if they change
COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY ./test/e2e/argocd-server-mock ./test/e2e/argocd-server-mock
COPY ./test/resources ./test/resources

RUN go build -o /usr/src/app/argocd-mock-server ./test/e2e/argocd-server-mock/main.go
RUN ls -la /usr/src/app/argocd-mock-server

################################################################################################
# image to be run by the GitHub Action job
################################################################################################
FROM registry.access.redhat.com/ubi9/ubi-minimal:latest as argocd-mock-server

# Copy the generated binary into the $PATH so it can be invoked
COPY --from=argocd-mock-server-builder /usr/src/app/argocd-mock-server /usr/local/bin/

ENV ARGOCD_SERVER_MOCK_TOKEN=secure-token
ENV ARGOCD_SERVER_MOCK_DEBUG=false
ENV ARGOCD_SERVER_MOCK_LISTEN_HOST=0.0.0.0
ENV ARGOCD_SERVER_MOCK_LISTEN_PORT=50084

# Run as non-root user
USER 1001

EXPOSE ${ARGOCD_SERVER_MOCK_LISTEN_PORT}

CMD /usr/local/bin/argocd-mock-server --debug $ARGOCD_SERVER_MOCK_DEBUG --listen $ARGOCD_SERVER_MOCK_LISTEN_HOST:$ARGOCD_SERVER_MOCK_LISTEN_PORT --token $ARGOCD_SERVER_MOCK_TOKEN